# Generated by Django 3.0.5 on 2025-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vin_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
